services:
  - type: web
    name: hand-gesture-recognition
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true

